language: ruby
rvm: 1.9.3
env:
  global:
  - DB=sqlite
bundler_args: --binstubs --without development:production
before_install: gem update bundler
before_script:
- RAILS_ENV=test rake db:create db:test:load --quiet
